// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4m6WVM6ByuoEc7g_T_rDyDLhGohW-f08',
    appId: '1:911014600437:web:fe7c9cfe718e672ed2efbc',
    messagingSenderId: '911014600437',
    projectId: 'dchat-remote',
    authDomain: 'dchat-remote.firebaseapp.com',
    storageBucket: 'dchat-remote.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEGbFmfZ4ckLZq2RZatJLCLrO9Q_FAipY',
    appId: '1:911014600437:android:a0732dafa2e0c34fd2efbc',
    messagingSenderId: '911014600437',
    projectId: 'dchat-remote',
    storageBucket: 'dchat-remote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrbbDIiYc6rq-Kr73j03WpzfsjvJ1zuNY',
    appId: '1:911014600437:ios:2da56a23eacbb8c3d2efbc',
    messagingSenderId: '911014600437',
    projectId: 'dchat-remote',
    storageBucket: 'dchat-remote.appspot.com',
    iosClientId: '911014600437-3k1660hl63q53iniejmu9hii3bp2mbkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.dchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrbbDIiYc6rq-Kr73j03WpzfsjvJ1zuNY',
    appId: '1:911014600437:ios:9ebd3e569274c295d2efbc',
    messagingSenderId: '911014600437',
    projectId: 'dchat-remote',
    storageBucket: 'dchat-remote.appspot.com',
    iosClientId: '911014600437-7i6lr7r85bp30uemo2aimq3s9att73pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.dchat.RunnerTests',
  );
}
